/**
 * The live season's team page, as a file.
 *
 * ── WHY ───────────────────────────────────────────────────────────────────
 *
 * Every team page on this site is prebuilt: `output: "export"` writes the
 * numbers into 30,000 HTML files and a change to any of them means another
 * build and another upload of the whole site. That is exactly right for the
 * archive, which is frozen — 2014 through SEASON_CEIL will never move again.
 *
 * It is exactly wrong for a season being played. Stats change nightly and
 * games arrive daily, and rebuilding the site every night to print them is an
 * hour of machine time for numbers that a fetch delivers in 30 ms.
 *
 * So the live season's page is DATA, not HTML. One file per team holding
 * precisely what loadTeamPageData would have returned, regenerated by the
 * nightly job and read by the browser. The archive keeps its baked pages and
 * pays nothing.
 *
 * ── WHY THE SAME COMPONENT RENDERS BOTH ───────────────────────────────────
 *
 * TeamPageView carries no "use client" directive, which makes it a SHARED
 * component: the frozen routes import it from a server component and it
 * renders on the server as it always has, while LiveTeamPage imports it from a
 * client component and the bundler compiles a client copy. Next's use-client
 * documentation is explicit that a directive is only needed on the files that
 * are entry points from a Server Component — so this costs the archive nothing
 * and needs no second implementation of a 1,000-line page.
 *
 * That mattered more than the bytes. A second team-page renderer for the live
 * season would drift from the archive's the first time either changed, and the
 * difference would show up as one season looking subtly unlike the others.
 *
 * ── WHAT THIS FILE IS ─────────────────────────────────────────────────────
 *
 * The codec, and nothing else. TeamPageData holds a Map and a Set, neither of
 * which survives JSON, so the two ends need one agreed shape — and they need
 * it in a module the CLIENT can import, which team-page-data.ts is not: it
 * reads the filesystem. Only the type crosses over, and `import type` erases.
 */
import type { TeamPageData } from "@/lib/team-page-data";

/** A TeamPageData with its Map and Set flattened. Everything else is already JSON. */
export type LiveTeamBundle =
  Omit<TeamPageData, "confRecords" | "rankedPlayerIds"> & {
    confRecords: Array<[number, TeamPageData["confRecords"] extends Map<number, infer V> ? V : never]>;
    rankedPlayerIds: number[];
    /** When the nightly job wrote this, for the "updated" line and for debugging a stale file. */
    builtAt: string;
  };

export function encodeLiveTeamPage(d: TeamPageData, builtAt = new Date().toISOString()): LiveTeamBundle {
  const { confRecords, rankedPlayerIds, ...rest } = d;
  /**
   * TRIMMED TO THIS ROSTER. The full set is every ranked player in site
   * history — around 25,000 ids, which would be more than half the file and
   * all of it irrelevant. Every read of it is `rankedPlayerIds.has(
   * p.bart_player_id)` against a player on THIS roster (sortable-roster-table,
   * player-headshot-strip), so the restriction is not an approximation: the
   * answers are identical for every question the page can ask.
   */
  const onRoster = new Set<number>();
  for (const p of rest.roster) {
    if (p.bart_player_id !== null && rankedPlayerIds.has(p.bart_player_id)) onRoster.add(p.bart_player_id);
  }
  return { ...rest, confRecords: [...confRecords], rankedPlayerIds: [...onRoster], builtAt };
}

export function decodeLiveTeamPage(b: LiveTeamBundle): TeamPageData {
  const { confRecords, rankedPlayerIds, builtAt: _builtAt, ...rest } = b;
  return {
    ...rest,
    confRecords: new Map(confRecords),
    rankedPlayerIds: new Set(rankedPlayerIds),
  } as TeamPageData;
}

/** Where one team's live bundle lives. Public path; dataUrl routes it to R2. */
export const liveTeamPath = (slug: string) => `/data/live/team/${slug}.json`;
