/**
 * Build-time static data loader. All reads go through `public/data/*.json`
 * (generated by `npm run export:data`) — Supabase is never touched at runtime.
 *
 * Used by server components / generateStaticParams. The functions are async to
 * preserve the existing call sites that expected promises.
 */
import fs from "node:fs/promises";
import path from "node:path";

const DATA = path.resolve("public/data");

async function readJson<T>(rel: string): Promise<T> {
  const text = await fs.readFile(path.join(DATA, rel), "utf8");
  return JSON.parse(text) as T;
}

// ---------- types matching the static JSON shape ----------
export type RankedStat = {
  key: string;
  label: string;
  format: "num1" | "num2" | "pct1" | "intDiff";
  value: number;
  rank: number;
  total: number;
};


export type StaticTeamSeasonRow = {
  id: number;
  name: string;
  conference: string | null;
  year: number;
  bta_rtg: number | null;            // pre-computed at build time
  bta_rank: number | null;           // rank within season cohort (1 = best)
  // Aggregated at export time from game_logs: count of (wins, losses, games)
  // where REB Diff > 0 AND FBP Diff > 0 AND 3PM Diff > 0 for that game.
  four_factor_record?: { wins: number; losses: number; games: number } | null;
  coach?: string | null;             // head coach (synced separately; nullable)
  // National-rank top-5 strengths + bottom-5 weaknesses for this season.
  // Computed at export time over the year's full D-I cohort. Each entry has
  // its raw value, rank, and total teams ranked so the UI can render
  // percentile-colored chips.
  national_ranks?: {
    top: Array<RankedStat>;
    bottom: Array<RankedStat>;
  };
  team_trank_stats: {
    rank: number | null; record: string | null;
    wins: number | null; losses: number | null;
    adjoe: number | null; adjde: number | null;
    adjt: number | null;
    wab: number | null; sos: number | null;
    ncsos: number | null; consos: number | null;
  };
  team_cbba_stats: {
    efg_pct: number | null; ts_pct: number | null;
    tov_pct: number | null; orb_pct: number | null;
    fta_rate: number | null; fg3_pct: number | null;
    fg3a_rate: number | null; ast_pct: number | null;
    efg_pct_def: number | null; tov_pct_def: number | null;
    orb_pct_def: number | null; fg3_pct_def: number | null;
    ortg: number | null; drtg: number | null;
    net_rtg: number | null; ortg_adj: number | null;
    drtg_adj: number | null; net_rtg_adj: number | null;
    pace: number | null; pace_adj: number | null;
    fbpts_pct: number | null; pitp_pct: number | null;
    fg3_made_diff?: number | null; orb_diff_ct?: number | null;
    reb_diff?: number | null; fbpts_diff?: number | null;
    potov_diff?: number | null;
  } | null;
  /** Pre-computed roster percentile chips, keyed by bart_player_id.
   *  Populated by scripts/embed-roster-ranks.mjs. Lets the team dossier
   *  render chips inline without any extra file reads at build time. */
  roster_ranks?: Record<number, {
    bta_portg?: number; pir?: number;
    pts?: number; reb?: number; ast?: number;
    fg3_pct?: number; ft_pct?: number;
  }>;
};

export type StaticPlayerRow = {
  id: number;
  bart_player_id: number | null;
  name: string;
  year: number;
  class: string | null;
  height: string | null;
  hometown: string | null;
  teams: { id: number; name: string; conference: string | null } | Array<{ id: number; name: string; conference: string | null }>;
  player_bart_stats: {
    raw_row: Array<string | number | null> | null;
    games: number | null;
    notes: string | null;
    projection: number | null;
  };
};

export type StaticIndex = {
  teamSlugs: string[];
  playerIds: number[];
  generated_at: string;
};

// ---------- public API ----------
export async function readIndex(): Promise<StaticIndex> {
  return readJson<StaticIndex>("index.json");
}

export async function readAllTeams(): Promise<StaticTeamSeasonRow[]> {
  return readJson<StaticTeamSeasonRow[]>("teams-all.json");
}

export async function readTeam(slug: string): Promise<{ name: string; seasons: StaticTeamSeasonRow[] } | null> {
  try {
    return await readJson<{ name: string; seasons: StaticTeamSeasonRow[] }>(`team/${slug}.json`);
  } catch {
    return null;
  }
}

export async function readPlayersForYear(year: number): Promise<StaticPlayerRow[]> {
  return readJson<StaticPlayerRow[]>(`players-by-year/${year}.json`);
}

/**
 * One transfer-portal entry for a specific player. Surface this on the
 * player profile hero when the player has committed elsewhere — we strike
 * through their current school and show the new destination.
 */
export type PortalEntry = {
  cbba_player_id: number;
  bart_player_id: number | null;
  name: string;
  status: "Active" | "Transferred" | "Withdrew";
  team_from: string | null;
  conf_from: string | null;
  team_to: string | null;
  conf_to: string | null;
  date_entered: string | null;
  date_updated: string | null;
};

let _portalCache: PortalEntry[] | null = null;
async function readPortal(): Promise<PortalEntry[]> {
  if (_portalCache) return _portalCache;
  try {
    const portal = await readJson<{ entries: PortalEntry[] }>("portal.json");
    _portalCache = portal.entries;
    return _portalCache;
  } catch {
    return [];
  }
}

/**
 * Per-player percentile ranks across ~20 stats, cohorted by year × position
 * bucket (G/F/C). Pre-computed by scripts/compute-player-ranks.mjs.
 */
export type PlayerStatRank = {
  value: number;
  percentile: number;     // 1-100 (higher = better, with direction already applied)
};
export type PlayerRanksSeason = {
  year: number;
  bucket: "G" | "F" | "C";
  cohortSize: number;
  stats: Record<string, PlayerStatRank>;
};
export type PlayerRanks = {
  bartId: number;
  seasonRanks: PlayerRanksSeason[];
};
export async function readPlayerRanks(bartId: number): Promise<PlayerRanks | null> {
  try {
    return await readJson<PlayerRanks>(`player-ranks/${bartId}.json`);
  } catch {
    return null;
  }
}


/**
 * Set of bart_player_ids that get a profile page. This is the union of:
 *
 *   1. Cohort-ranked players — those with a `player-ranks/<id>.json` file
 *      (cleared the 18g/18mpg/5ppg + position-bucket eligibility floor in
 *      compute-player-ranks.mts).
 *   2. Freshmen — anyone whose most-recent season carries class === "Fr".
 *      They're always clickable so a current-year freshman who hasn't yet
 *      accrued the minutes/PPG to land in a cohort still has a profile.
 *      Their "Where they rank" section just won't render (no rank file).
 *
 * Drives:
 *   - generateStaticParams() in /players/[id]/page.tsx
 *   - Roster / table render logic (clickable name vs plain text).
 *
 * Module-level cache so the directory + per-year scans happen once per build.
 */
// Internal helper: name-derived slug. Mirrors the `coachSlug()` used by
// /coaches/[slug]/page.tsx's generateStaticParams, so links from the team
// page land on a real route (the SR slug in coach-history has "-1" suffixes
// that the profile route doesn't honor).
function nameToCoachSlug(name: string): string {
  return name.toLowerCase().normalize("NFKD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

// Normalize the SR `round` field to a compact, sortable label. SR uses both
// modern and legacy names ("Round of 32" vs "R32", "Third Round" in 2010-15
// = R32, etc).
function normalizeRound(raw: string | null): string | null {
  if (!raw) return null;
  const r = raw.toLowerCase().trim();
  if (r.includes("champion")) return "Champion";
  if (r.includes("runner") || r === "finals" || r === "national runner-up") return "Runner-Up";
  if (r.includes("final four") || r === "f4" || r === "ff") return "F4";
  if (r.includes("elite") || r === "e8") return "E8";
  if (r.includes("sweet") || r === "s16") return "S16";
  if (r === "r32" || r.includes("round of 32") || r === "third round" || r === "second round") return "R32";
  if (r === "r64" || r.includes("round of 64") || r === "first round" || r === "second round")  return "R64";
  if (r.includes("first four") || r.includes("play-in")) return "First Four";
  if (r.includes("did not")) return null;
  return raw;
}

/**
 * Per-team season history pulled from src/data/coach-history.json (SR scrape),
 * keyed by team name → year. Carries conference record + the head coach for
 * that year. Cached module-level so the disk read happens once per build.
 */
export type ConfRecord = {
  wins: number | null;
  losses: number | null;
  coachName: string | null;
  coachSlug: string | null;
  // Tournament results — both null if the team missed the dance that year.
  // `tourneyRound` is normalized: "Champion" | "Runner-Up" | "F4" | "E8" |
  //   "S16" | "R32" | "R64" | "First Four" | other-as-is.
  tourneyRound: string | null;
  tourneySeed: number | null;
};
let _confRecordsCache: Map<string, Map<number, ConfRecord>> | null = null;
export async function readConfRecordsByTeam(): Promise<Map<string, Map<number, ConfRecord>>> {
  if (_confRecordsCache) return _confRecordsCache;
  try {
    const historyPath = path.resolve("src/data/coach-history.json");
    const raw = JSON.parse(await fs.readFile(historyPath, "utf8")) as Record<
      string,
      Record<string, {
        name?: string | null;
        slug?: string | null;
        conf_wins?: number | null;
        conf_losses?: number | null;
        round?: string | null;
        seed?: number | null;
      }>
    >;
    const out = new Map<string, Map<number, ConfRecord>>();
    for (const [team, years] of Object.entries(raw)) {
      const m = new Map<number, ConfRecord>();
      for (const [yStr, season] of Object.entries(years)) {
        const y = parseInt(yStr, 10);
        if (!Number.isFinite(y)) continue;
        const hasConf = season.conf_wins != null && season.conf_losses != null;
        const hasCoach = !!season.name;
        if (!hasConf && !hasCoach) continue;
        m.set(y, {
          wins: season.conf_wins ?? null,
          losses: season.conf_losses ?? null,
          coachName: season.name ?? null,
          coachSlug: season.name ? nameToCoachSlug(season.name) : null,
          tourneyRound: normalizeRound(season.round ?? null),
          tourneySeed: typeof season.seed === "number" ? season.seed : null,
        });
      }
      if (m.size > 0) out.set(team, m);
    }
    _confRecordsCache = out;
    return out;
  } catch {
    return new Map();
  }
}

/**
 * Per-game records for an entire year (every team's full schedule). Loaded
 * once per year, cached. Use to drive per-team schedule strips / tickers.
 */
export type GameLog = {
  game_date: string;
  team_id: number;
  team_name: string | null;
  opp_team_market: string | null;
  // CBB Analytics game ID — string in the game-logs format
  // "<numeric>-<team_id>-game-<bool>". The leading numeric prefix is the
  // shared game ID across both teams' game-log rows and matches the
  // team-games/<year>/<numeric>.json box-score file.
  cbba_game_id?: string | null;
  is_home: boolean | null;
  is_neutral: boolean | null;
  won: boolean | null;
  pts_scored: number | null;
  pts_against: number | null;
  // Diffs (team vs opp). Present on most rows, occasionally null.
  pts_diff?: number | null;
  reb_diff?: number | null;
  orb_diff?: number | null;
  tov_diff?: number | null;
  fbpts_diff?: number | null;
  fg3_made_diff?: number | null;
  // Shooting % for the team in this game.
  efg_pct?: number | null;
  ts_pct?: number | null;
  fg3_pct?: number | null;
  ft_pct?: number | null;
  // Optional round label, attached only when the GameLog is being rendered
  // inside a tournament-themed ticker (e.g. March Madness resume). One of
  // "R1" "R2" "S16" "E8" "F4" "NC" — see SHORT_ROUND in coach page.
  tournamentRound?: string | null;
};
const _gameLogsCache = new Map<number, GameLog[]>();
export async function readGameLogsForYear(year: number): Promise<GameLog[]> {
  if (_gameLogsCache.has(year)) return _gameLogsCache.get(year)!;
  try {
    const games = await readJson<GameLog[]>(`game-logs-by-year/${year}.json`);
    _gameLogsCache.set(year, games);
    return games;
  } catch {
    _gameLogsCache.set(year, []);
    return [];
  }
}

// Earliest season-year we have player data for. Used by the freshman pass in
// readRankedPlayerIds — keep in sync with the export pipeline.
const FRESHMAN_SCAN_START_YEAR = 2013;

let _rankedPlayerIdsCache: Set<number> | null = null;
export async function readRankedPlayerIds(): Promise<Set<number>> {
  if (_rankedPlayerIdsCache) return _rankedPlayerIdsCache;
  const ids = new Set<number>();
  try {
    const files = await fs.readdir(path.join(DATA, "player-ranks"));
    for (const f of files) {
      if (!f.endsWith(".json")) continue;
      const n = parseInt(f.replace(".json", ""), 10);
      if (Number.isFinite(n)) ids.add(n);
    }
  } catch { /* no rank files yet — fall through to freshman pass */ }

  // Freshman pass: walk every year's players-by-year file, track each
  // bart_player_id's MOST RECENT (year, class). If their latest season was a
  // freshman year, they get a profile page regardless of stat thresholds.
  // Captures both current-year freshmen and one-and-done careers.
  try {
    const latestByBartId = new Map<number, { year: number; cls: string | null }>();
    for (let year = FRESHMAN_SCAN_START_YEAR; year <= LATEST_PLAYER_YEAR; year++) {
      let list: StaticPlayerRow[] = [];
      try {
        list = await readJson<StaticPlayerRow[]>(`players-by-year/${year}.json`);
      } catch { continue; }
      for (const p of list) {
        const bartId = p.bart_player_id;
        if (bartId == null || !Number.isFinite(bartId)) continue;
        const prev = latestByBartId.get(bartId);
        if (!prev || prev.year < year) {
          latestByBartId.set(bartId, { year, cls: p.class ?? null });
        }
      }
    }
    for (const [bartId, latest] of latestByBartId) {
      if (latest.cls === "Fr") ids.add(bartId);
    }
  } catch { /* tolerate any I/O hiccup — ranked set is still useful */ }

  _rankedPlayerIdsCache = ids;
  return ids;
}

// Newest season we'll scan for the freshman pass. Mirrors LATEST_YEAR in
// coaches.ts; duplicated here to avoid a circular import.
const LATEST_PLAYER_YEAR = 2026;

/**
 * Per-player situational splits derived from the box-score data: home/away,
 * win/loss, conf/non-conf, plus best/worst game per season. Pre-computed by
 * scripts/compute-player-splits.mjs.
 */
export type SplitAgg = {
  games: number;
  ppg: number; rpg: number; apg: number; spg: number; bpg: number; tov_pg: number;
  fg_pct: number | null;
  fg3_pct: number | null;
  ft_pct: number | null;
  ts_pct: number | null;
} | null;

export type GameSummary = {
  date: string | null;
  opp: string | null;
  is_home: boolean | null;
  is_neutral: boolean | null;
  won: boolean | null;
  mins: number | null;
  pts: number | null;
  reb: number | null;
  ast: number | null;
  stl: number | null;
  blk: number | null;
  tov: number | null;
  fgm: number | null; fga: number | null;
  fgm3: number | null; fga3: number | null;
  ftm: number | null; fta: number | null;
};

export type PlayerSplitsSeason = {
  year: number;
  splits: {
    home: SplitAgg;
    away: SplitAgg;
    neutral: SplitAgg;
    win: SplitAgg;
    loss: SplitAgg;
    conf: SplitAgg;
    nonConf: SplitAgg;
    all: SplitAgg;
  };
  bestGame: GameSummary | null;
  worstGame: GameSummary | null;
};
export type PlayerSplits = {
  bartId: number;
  seasonSplits: PlayerSplitsSeason[];
};
export async function readPlayerSplits(bartId: number): Promise<PlayerSplits | null> {
  try {
    return await readJson<PlayerSplits>(`player-splits/${bartId}.json`);
  } catch {
    return null;
  }
}

/**
 * Look up a player's portal entry by their Bart Torvik ID. Returns the latest
 * entry (most recently updated) when the player has multiple — players who
 * enter and re-enter the portal across cycles can have several rows.
 */
export async function readPortalEntryForBartId(bartId: number): Promise<PortalEntry | null> {
  const all = await readPortal();
  const matches = all.filter((e) => e.bart_player_id === bartId);
  if (matches.length === 0) return null;
  matches.sort((a, b) => (b.date_updated ?? "").localeCompare(a.date_updated ?? ""));
  return matches[0]!;
}

export async function readPlayer(bartId: number): Promise<{
  bart_player_id: number;
  seasons: Array<{
    year: number;
    team_name: string;
    team_conference: string | null;
    class: string | null;
    raw_row: Array<string | number | null> | null;
    games: number | null;
    notes: string | null;
    projection: number | null;
  }>;
} | null> {
  try {
    return await readJson(`player/${bartId}.json`);
  } catch {
    return null;
  }
}

export async function readConferences(year: number): Promise<string[]> {
  const all = await readJson<Record<string, string[]>>("conferences.json");
  return all[String(year)] ?? [];
}
