/**
 * Build-time static data loader. All reads go through `public/data/*.json`
 * (generated by `npm run export:data`) — Supabase is never touched at runtime.
 *
 * Used by server components / generateStaticParams. The functions are async to
 * preserve the existing call sites that expected promises.
 */
import fs from "node:fs/promises";
import { isUsableSeason, isExhibitionGame } from "@/lib/seasons";
import path from "node:path";

const DATA = path.resolve("public/data");

export async function readJson<T>(rel: string): Promise<T> {
  const text = await fs.readFile(path.join(DATA, rel), "utf8");
  return JSON.parse(text) as T;
}

// ---------- types matching the static JSON shape ----------
export type RankedStat = {
  key: string;
  label: string;
  format: "num1" | "num2" | "pct1" | "intDiff";
  value: number;
  rank: number;
  total: number;
};


export type StaticTeamSeasonRow = {
  id: number;
  name: string;
  conference: string | null;
  year: number;
  bta_rtg: number | null;            // pre-computed at build time
  bta_rank: number | null;           // rank within season cohort (1 = best)
  // Aggregated at export time from game_logs: count of (wins, losses, games)
  // where REB Diff > 0 AND FBP Diff > 0 AND 3PM Diff > 0 for that game.
  four_factor_record?: { wins: number; losses: number; games: number } | null;
  coach?: string | null;             // head coach (synced separately; nullable)
  // National-rank top-5 strengths + bottom-5 weaknesses for this season.
  // Computed at export time over the year's full D-I cohort. Each entry has
  // its raw value, rank, and total teams ranked so the UI can render
  // percentile-colored chips.
  national_ranks?: {
    top: Array<RankedStat>;
    bottom: Array<RankedStat>;
  };
  team_trank_stats: {
    rank: number | null; record: string | null;
    wins: number | null; losses: number | null;
    adjoe: number | null; adjde: number | null;
    adjt: number | null;
    wab: number | null; sos: number | null;
    ncsos: number | null; consos: number | null;
  };
  /**
   * Season aggregates summed from the CBBD box archive by
   * scripts/build-team-season-stats.mjs. Replaced `team_cbba_stats`.
   *
   * `pace_adj` is gone (Bart's `adjt` in team_trank_stats is the same concept
   * from a source we already carry), as are the raw fg3_*_def counts that only
   * existed so the client could divide them into an opponent 3P% — that is now
   * computed from season totals at build time.
   */
  team_season_stats: {
    games?: number | null;
    efg_pct: number | null; ts_pct: number | null;
    tov_pct: number | null; orb_pct: number | null;
    fta_rate: number | null; fg3_pct: number | null;
    fg3a_rate: number | null; ast_pct: number | null;
    efg_pct_def: number | null; tov_pct_def: number | null;
    orb_pct_def: number | null; fg3_pct_def: number | null;
    ortg: number | null; drtg: number | null;
    net_rtg: number | null; ortg_adj: number | null;
    drtg_adj: number | null; net_rtg_adj: number | null;
    /**
     * Our own schedule-adjusted ratings (scripts/build-adjusted-ratings.mjs) —
     * the same aNET/aORTG/aDRTG the explorer sorts on by default. Present in
     * teams-all.json since that script landed; they were simply never declared
     * here, so anything reading them off a StaticTeamSeasonRow had to widen the
     * type by hand.
     */
    a_net?: number | null; a_ortg?: number | null; a_drtg?: number | null;
    pace: number | null;
    fbpts_pct: number | null; pitp_pct: number | null; pot_pct?: number | null;
    fg3_made_diff?: number | null; orb_diff_ct?: number | null;
    reb_diff?: number | null; fbpts_diff?: number | null;
    potov_diff?: number | null;
    /** Games in which each point split was actually tracked — see trackedSplit. */
    fbpts_games?: number | null; pitp_games?: number | null; potov_games?: number | null;
  } | null;
  /** Pre-computed roster percentile chips, keyed by bart_player_id.
   *  Populated by scripts/embed-roster-ranks.mjs. Lets the team dossier
   *  render chips inline without any extra file reads at build time. */
  roster_ranks?: Record<number, {
    pir?: number;
    pts?: number; reb?: number; ast?: number;
    fg3_pct?: number; ft_pct?: number;
  }>;
};

export type StaticPlayerRow = {
  id: number;
  bart_player_id: number | null;
  name: string;
  year: number;
  class: string | null;
  height: string | null;
  hometown: string | null;
  teams: { id: number; name: string; conference: string | null } | Array<{ id: number; name: string; conference: string | null }>;
  player_bart_stats: {
    raw_row: Array<string | number | null> | null;
    games: number | null;
    notes: string | null;
    projection: number | null;
  };
};

export type StaticIndex = {
  teamSlugs: string[];
  playerIds: number[];
  generated_at: string;
};

// ---------- public API ----------
export async function readIndex(): Promise<StaticIndex> {
  return readJson<StaticIndex>("index.json");
}

// The team-season exports still carry full history, so gate here to match the
// site-wide window defined in src/lib/seasons.ts — floor 2013-14 plus the
// excluded 2020-21 COVID season.

/**
 * CACHED, because this is the single most expensive read in the build.
 *
 * teams-all.json is 12 MB and takes ~51 ms to read and parse — measured — and
 * every team page calls this once. At 5,009 team pages that was already about
 * six minutes of the build spent re-parsing one unchanging file; with the tab
 * split taking team-ish pages past 30,000 it would have been thirty.
 *
 * The cache holds the FILTERED array, so callers cannot mutate the shared copy
 * through a filter of their own. Note they can still sort it in place — the
 * same caveat processTeams() documents about its own cohort cache.
 *
 * Memory: one parse of a 12 MB document, held for the life of the process.
 * That is a build-time process with --max-old-space-size set well above it,
 * and a long-lived server would want this file behind a revalidate anyway.
 */
let _allTeamsCache: StaticTeamSeasonRow[] | null = null;
export async function readAllTeams(): Promise<StaticTeamSeasonRow[]> {
  if (_allTeamsCache) return _allTeamsCache;
  const all = await readJson<StaticTeamSeasonRow[]>("teams-all.json");
  _allTeamsCache = all.filter((t) => isUsableSeason(t.year));
  return _allTeamsCache;
}

/**
 * One team's NET rank in each of the given seasons — where its aNET sits in
 * that year's D-I cohort, 1 = best.
 *
 * Computed here at build time rather than stored, because it is a pure function
 * of teams-all.json, which every caller already has open. Storing it would mean
 * a data re-export to change a display detail, and a second number that can
 * drift out of step with the aNET it ranks.
 *
 * Standard competition ranking: ties share the better position (two teams at
 * the top are both #1, the next is #3). A team with no aNET for a year is
 * absent from the result rather than ranked last — no rating is not a bad one.
 */
export function netRanksForTeam(
  allTeams: StaticTeamSeasonRow[],
  teamName: string,
  years: number[],
): Record<number, number> {
  const want = new Set(years);
  // One pass, not one per year: these pages call this with up to 13 seasons
  // against ~6,700 rows.
  const mine = new Map<number, number>();
  const cohort = new Map<number, number[]>();
  for (const t of allTeams) {
    if (!want.has(t.year)) continue;
    const v = t.team_season_stats?.a_net;
    if (typeof v !== "number") continue;
    (cohort.get(t.year) ?? cohort.set(t.year, []).get(t.year)!).push(v);
    if (t.name === teamName) mine.set(t.year, v);
  }
  const out: Record<number, number> = {};
  for (const [year, v] of mine) {
    const all = cohort.get(year) ?? [];
    let better = 0;
    for (const other of all) if (other > v) better++;
    out[year] = better + 1;
  }
  return out;
}

/**
 * One team's eight-way stat splits for a season, or null when the season has
 * no splits file (pre-2014 seasons have no per-game box archive).
 *
 * Reads the whole season's file — ~1.2 MB — and hands back only this team's
 * rows, which is a few KB. That is deliberate: the file is read once per season
 * and cached, so 365 team pages share one parse, and nothing ships to the
 * browser except the one team's numbers.
 */
const _splitsCache = new Map<number, TeamSplitsFile | null>();
type TeamSplitsFile = {
  season: number;
  splits: { key: string; label: string }[];
  stats: { key: string; group: string; label: string; fmt: "num1" | "pct1" | "x2" }[];
  groups: Record<string, string>;
  teams: Record<string, Record<string, { games: number; v: (number | null)[]; p: (number | null)[] }>>;
};

export async function readTeamSplits(year: number, teamName: string) {
  if (!_splitsCache.has(year)) {
    try {
      _splitsCache.set(year, await readJson<TeamSplitsFile>(`team-splits/${year}.json`));
    } catch {
      _splitsCache.set(year, null);
    }
  }
  const file = _splitsCache.get(year);
  const rows = file?.teams?.[teamName];
  if (!file || !rows) return null;
  return { season: file.season, splits: file.splits, stats: file.stats, groups: file.groups, rows };
}

/* ------------------------------------------------------------------ *
 * Play-by-play derivatives: the assist network and the shot-clock splits.
 *
 * Both are ONE file for every team-season rather than one per year, and both
 * are read at BUILD time — a team page is prebuilt, so the whole file is
 * parsed once for the run and only the team's own slice reaches the HTML. The
 * file's size is therefore a build concern, not a payload concern, which is
 * what lets the assist network keep sixty edges per team-season.
 * ------------------------------------------------------------------ */

export type AssistNetwork = {
  games: number;
  /** [passerBartId, shooterBartId, total, rim, mid, three] */
  edges: [number, number, number, number, number, number][];
  players: Record<string, {
    fgm: number;
    ast_given: number;
    ast_rate: number | null;
    rim_ast_rate: number | null;
    mid_ast_rate: number | null;
    three_ast_rate: number | null;
  }>;
  names: Record<string, string>;
};

export type ClockSplits = {
  clock_games: number;
  dropped_rate: number | null;
  early_rate: number | null; mid_rate: number | null; late_rate: number | null;
  early_efg: number | null; mid_efg: number | null; late_efg: number | null;
  early_rate_def: number | null; mid_rate_def: number | null; late_rate_def: number | null;
  early_efg_def: number | null; mid_efg_def: number | null; late_efg_def: number | null;
};

let _assistCache: Record<string, AssistNetwork> | null | undefined;
let _clockCache: Record<string, ClockSplits> | null | undefined;

/** Who fed whom, for one team-season. Null before 2014 (no play-by-play). */
export async function readAssistNetwork(
  year: number,
  teamName: string,
): Promise<AssistNetwork | null> {
  if (_assistCache === undefined) {
    _assistCache = await readJson<Record<string, AssistNetwork>>("assist-network.json").catch(() => null);
  }
  return _assistCache?.[`${teamName}|${year}`] ?? null;
}

export type AssistPlayerSeason = {
  team: string;
  /** [otherBartId, count] — who this player set up, biggest first. */
  fed: [number, number][];
  /** [otherBartId, count] — who set this player up. */
  fed_by: [number, number][];
  fgm: number;
  ast_given: number;
  ast_rate: number | null;
  rim_ast_rate: number | null;
  mid_ast_rate: number | null;
  three_ast_rate: number | null;
};

type AssistPlayersFile = {
  names: Record<string, string>;
  players: Record<string, AssistPlayerSeason>;
};

/** year → the whole season's player view, parsed once per build. */
const _assistPlayersCache = new Map<number, AssistPlayersFile | null>();

/**
 * One player's assist connections for one season, with the names of everyone
 * on the other end of them.
 *
 * Keyed by year rather than by player because the per-player alternative is
 * 12,000-odd files for a panel that is a dozen rows — the year file is read
 * once for the build and every player page in that season shares the parse.
 */
export async function readAssistForPlayer(
  year: number,
  bartId: number,
): Promise<{ season: AssistPlayerSeason; names: Record<string, string> } | null> {
  if (!_assistPlayersCache.has(year)) {
    _assistPlayersCache.set(
      year,
      await readJson<AssistPlayersFile>(`assist-players/${year}.json`).catch(() => null),
    );
  }
  const file = _assistPlayersCache.get(year);
  const season = file?.players?.[String(bartId)];
  if (!file || !season) return null;
  return { season, names: file.names };
}

/** Shot selection and efficiency by shot-clock position. Null before 2014. */
export async function readClockSplits(
  year: number,
  teamName: string,
): Promise<ClockSplits | null> {
  if (_clockCache === undefined) {
    _clockCache = await readJson<Record<string, ClockSplits>>("clock-splits.json").catch(() => null);
  }
  return _clockCache?.[`${teamName}|${year}`] ?? null;
}

export async function readTeam(slug: string): Promise<{ name: string; seasons: StaticTeamSeasonRow[] } | null> {
  try {
    const t = await readJson<{ name: string; seasons: StaticTeamSeasonRow[] }>(`team/${slug}.json`);
    return { ...t, seasons: t.seasons.filter((s) => isUsableSeason(s.year)) };
  } catch {
    return null;
  }
}

/**
 * CACHED per season — ~19 ms a parse, and every team page for a season reads
 * the same file. Keyed by year rather than held as one blob so a build that
 * only touches recent seasons never parses the older ones.
 */
const _playersByYearCache = new Map<number, StaticPlayerRow[]>();
export async function readPlayersForYear(year: number): Promise<StaticPlayerRow[]> {
  const hit = _playersByYearCache.get(year);
  if (hit) return hit;
  const rows = await readJson<StaticPlayerRow[]>(`players-by-year/${year}.json`);
  _playersByYearCache.set(year, rows);
  return rows;
}

/**
 * bart_player_id → EPM for a season, for the roster columns. Prefers the real
 * play-by-play EPM (epm-<year>.json); fills any gaps with the estimated
 * box-epm. Empty map when neither file exists.
 */
export async function readImpactForYear(year: number): Promise<Map<number, number>> {
  const out = new Map<number, number>();
  const real = await readJson<{ players: Record<string, { epm: number }> }>(`epm-${year}.json`).catch(() => null);
  if (real?.players) for (const [bid, v] of Object.entries(real.players)) {
    if (typeof v.epm === "number") out.set(Number(bid), v.epm);
  }
  const box = await readJson<{ players: Record<string, { epm: number }> }>(`box-epm-${year}.json`).catch(() => null);
  if (box?.players) for (const [bid, v] of Object.entries(box.players)) {
    const id = Number(bid);
    if (!out.has(id) && typeof v.epm === "number") out.set(id, v.epm);
  }
  return out;
}

/**
 * eWins and raw on/off for a season, keyed by bart id.
 *
 * Deliberately reads ONLY epm-<year>.json, with no box-epm fallback. The box
 * estimate is a projection from a box line; it has no lineup information, so it
 * cannot produce an on/off at all and its eWins would be a different quantity
 * wearing the same label. A player covered only by the box fit gets nothing
 * here and renders as "—", which is the same thing the player-page Impact panel
 * does with these two.
 */
/**
 * Memoized per year. epm-<year>.json is ~280 KB and this is now read from the
 * PLAYER page, which is generated ~15,700 times — re-reading and re-parsing it
 * per page would add gigabytes of parsing to a build that already takes seven
 * minutes. The file is static for the whole build, so one parse per year is
 * the whole cost. Matches _rankedPlayerIdsCache below.
 */
export type ImpactExtras = {
  ewins: number | null;
  on_off: number | null;
  /** Offensive and defensive halves of EPM. The player hero splits the total
   *  into the two sides, which is the only place the sign of a defensive
   *  contribution is visible without opening the Impact panel. */
  off: number | null;
  def: number | null;
};

const _impactExtrasCache = new Map<number, Map<number, ImpactExtras>>();

export async function readImpactExtrasForYear(
  year: number,
): Promise<Map<number, ImpactExtras>> {
  const cached = _impactExtrasCache.get(year);
  if (cached) return cached;
  const out = new Map<number, ImpactExtras>();
  const real = await readJson<{
    players: Record<string, { ewins?: number | null; on_off?: number | null; off?: number | null; def?: number | null }>;
  }>(`epm-${year}.json`).catch(() => null);
  if (real?.players) for (const [bid, v] of Object.entries(real.players)) {
    const num = (x: unknown) => (typeof x === "number" && Number.isFinite(x) ? x : null);
    out.set(Number(bid), { ewins: num(v.ewins), on_off: num(v.on_off), off: num(v.off), def: num(v.def) });
  }
  _impactExtrasCache.set(year, out);
  return out;
}

/**
 * NBA draft record for a college player, by name.
 *
 * Memoized for the same reason readImpactExtrasForYear is: the player page is
 * generated ~15,700 times and this file would otherwise be read and parsed once
 * per page. Keyed on the same normalized name the client-side pill uses, so the
 * hero and the roster pill can never disagree about who was drafted.
 */
export type NbaDraftRecord = { year: number; pick: number | null; team: string | null; college: string | null };

let _drafteesCache: Record<string, NbaDraftRecord> | null = null;

export async function readNbaDraftee(name: string | null): Promise<NbaDraftRecord | null> {
  if (!name) return null;
  if (!_drafteesCache) {
    _drafteesCache = await readJson<Record<string, NbaDraftRecord>>("nba-draftees.json").catch(() => ({}));
  }
  const key = normPersonName(name);
  return _drafteesCache[key] ?? null;
}

/** Lowercase, unaccented, punctuation-free, generational suffix dropped. The
 *  one key every name-matched lookup here uses, so they cannot disagree. */
function normPersonName(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
    .replace(/\s+/g, " ")
    .replace(/\s+(jr|sr|ii|iii|iv|v)$/i, "");
}

/**
 * One transfer-portal entry for a specific player. Surface this on the
 * player profile hero when the player has committed elsewhere — we strike
 * through their current school and show the new destination.
 */
export type PortalEntry = {
  cbba_player_id: number;
  bart_player_id: number | null;
  name: string;
  status: "Active" | "Transferred" | "Withdrew";
  team_from: string | null;
  conf_from: string | null;
  team_to: string | null;
  conf_to: string | null;
  date_entered: string | null;
  date_updated: string | null;
};

let _portalCache: PortalEntry[] | null = null;
async function readPortal(): Promise<PortalEntry[]> {
  if (_portalCache) return _portalCache;
  try {
    const portal = await readJson<{ entries: PortalEntry[] }>("portal.json");
    _portalCache = portal.entries;
    return _portalCache;
  } catch {
    return [];
  }
}

/**
 * Per-player percentile ranks across ~20 stats, cohorted by year × position
 * bucket (G/F/C). Pre-computed by scripts/compute-player-ranks.mjs.
 */
export type PlayerStatRank = {
  value: number;
  percentile: number;     // 1-100 (higher = better, with direction already applied)
};
export type PlayerRanksSeason = {
  year: number;
  bucket: "G" | "F" | "C";
  cohortSize: number;
  // Headline EPM leaderboard position for the player's bucket and across all
  // eligible D-I players in the same season. Null when the player has no epm
  // value for that year.
  rank: number | null;
  rankOverall: number | null;
  cohortOverall: number | null;
  // Mid-major (non-power-conf) rank — only populated when the player's own
  // conference is NOT a power league (ACC/B10/B12/P12/SEC/BE). Null for
  // power-conf players, since "mid-major" wouldn't apply to them.
  rankNonPower: number | null;
  cohortNonPower: number | null;
  stats: Record<string, PlayerStatRank>;
};
export type PlayerRanks = {
  bartId: number;
  seasonRanks: PlayerRanksSeason[];
};
/**
 * RSCI consensus high-school rank, by name.
 *
 * RSCI (rscihoops.com) is the consensus top-100 — the one recruiting ranking
 * the site is cleared to print; the per-service numbers from 247/ESPN/On3 are
 * not (docs/TODO-legal-sources.md).
 *
 * Coverage is the 2026 class only, which is the extent of what we hold: 324
 * rows, none of them carrying a bart id because none of them have played a
 * college game yet. So this resolves for almost nobody today and starts
 * resolving as that class plays. Matched on name and only when the name is
 * UNIQUE in the file — a rank hung on the wrong player is worse than no rank,
 * and there is no id to fall back on.
 *
 * Memoized for the same reason readNbaDraftee is: ~15,700 pages, one file.
 */
let _rsciCache: Map<string, number | null> | null = null;

export async function readRsciRank(name: string | null): Promise<number | null> {
  if (!name) return null;
  if (!_rsciCache) {
    _rsciCache = new Map();
    const body = await readJson<{ recruits: Array<{ name?: string; rsci?: number | null }> }>(
      "recruits-2026.json",
    ).catch(() => ({ recruits: [] }));
    const seen = new Set<string>();
    for (const r of body.recruits ?? []) {
      if (typeof r.name !== "string" || typeof r.rsci !== "number") continue;
      const k = normPersonName(r.name);
      if (!k) continue;
      // Second sighting of a name poisons it rather than overwriting — either
      // entry could be the one being asked about.
      if (seen.has(k)) _rsciCache.set(k, null);
      else {
        seen.add(k);
        _rsciCache.set(k, r.rsci);
      }
    }
  }
  const hit = _rsciCache.get(normPersonName(name));
  return typeof hit === "number" && hit >= 1 && hit <= 100 ? hit : null;
}

export async function readPlayerRanks(bartId: number): Promise<PlayerRanks | null> {
  try {
    return await readJson<PlayerRanks>(`player-ranks/${bartId}.json`);
  } catch {
    return null;
  }
}


/**
 * Set of bart_player_ids that get a profile page. This is the union of:
 *
 *   1. Cohort-ranked players — those with a `player-ranks/<id>.json` file
 *      (cleared the 18g/20mpg/5.3ppg + position-bucket eligibility floor in
 *      compute-player-ranks.mts).
 *   2. Freshmen — anyone whose most-recent season carries class === "Fr".
 *      They're always clickable so a current-year freshman who hasn't yet
 *      accrued the minutes/PPG to land in a cohort still has a profile.
 *      Their "Where they rank" section just won't render (no rank file).
 *
 * Drives:
 *   - generateStaticParams() in /players/[id]/page.tsx
 *   - Roster / table render logic (clickable name vs plain text).
 *
 * Module-level cache so the directory + per-year scans happen once per build.
 */
// Internal helper: name-derived slug. Mirrors the `coachSlug()` used by
// /coaches/[slug]/page.tsx's generateStaticParams, so links from the team
// page land on a real route (the SR slug in coach-history has "-1" suffixes
// that the profile route doesn't honor).
function nameToCoachSlug(name: string): string {
  return name.toLowerCase().normalize("NFKD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

// Normalize the SR `round` field to a compact, sortable label. SR uses both
// modern and legacy names ("Round of 32" vs "R32", "Third Round" in 2010-15
// = R32, etc).
function normalizeRound(raw: string | null): string | null {
  if (!raw) return null;
  const r = raw.toLowerCase().trim();
  if (r.includes("champion")) return "Champion";
  if (r.includes("runner") || r === "finals" || r === "national runner-up") return "Runner-Up";
  if (r.includes("final four") || r === "f4" || r === "ff") return "F4";
  if (r.includes("elite") || r === "e8") return "E8";
  if (r.includes("sweet") || r === "s16") return "S16";
  if (r === "r32" || r.includes("round of 32") || r === "third round" || r === "second round") return "R32";
  if (r === "r64" || r.includes("round of 64") || r === "first round" || r === "second round")  return "R64";
  if (r.includes("first four") || r.includes("play-in")) return "First Four";
  if (r.includes("did not")) return null;
  return raw;
}

/**
 * Per-team season history pulled from src/data/coach-history.json (SR scrape),
 * keyed by team name → year. Carries conference record + the head coach for
 * that year. Cached module-level so the disk read happens once per build.
 */
export type ConfRecord = {
  wins: number | null;
  losses: number | null;
  coachName: string | null;
  coachSlug: string | null;
  // Tournament results — both null if the team missed the dance that year.
  // `tourneyRound` is normalized: "Champion" | "Runner-Up" | "F4" | "E8" |
  //   "S16" | "R32" | "R64" | "First Four" | other-as-is.
  tourneyRound: string | null;
  tourneySeed: number | null;
};
let _confRecordsCache: Map<string, Map<number, ConfRecord>> | null = null;
export async function readConfRecordsByTeam(): Promise<Map<string, Map<number, ConfRecord>>> {
  if (_confRecordsCache) return _confRecordsCache;
  try {
    const historyPath = path.resolve("src/data/coach-history.json");
    const raw = JSON.parse(await fs.readFile(historyPath, "utf8")) as Record<
      string,
      Record<string, {
        name?: string | null;
        slug?: string | null;
        conf_wins?: number | null;
        conf_losses?: number | null;
        round?: string | null;
        seed?: number | null;
      }>
    >;
    const out = new Map<string, Map<number, ConfRecord>>();
    for (const [team, years] of Object.entries(raw)) {
      const m = new Map<number, ConfRecord>();
      for (const [yStr, season] of Object.entries(years)) {
        const y = parseInt(yStr, 10);
        if (!Number.isFinite(y)) continue;
        const hasConf = season.conf_wins != null && season.conf_losses != null;
        const hasCoach = !!season.name;
        if (!hasConf && !hasCoach) continue;
        m.set(y, {
          wins: season.conf_wins ?? null,
          losses: season.conf_losses ?? null,
          coachName: season.name ?? null,
          coachSlug: season.name ? nameToCoachSlug(season.name) : null,
          tourneyRound: normalizeRound(season.round ?? null),
          tourneySeed: typeof season.seed === "number" ? season.seed : null,
        });
      }
      if (m.size > 0) out.set(team, m);
    }
    _confRecordsCache = out;
    return out;
  } catch {
    return new Map();
  }
}

/**
 * Per-game records for an entire year (every team's full schedule). Loaded
 * once per year, cached. Use to drive per-team schedule strips / tickers.
 */
export type GameLog = {
  game_date: string;
  team_id: number;
  team_name: string | null;
  opp_team_market: string | null;
  // Game id in the log format "<cbbdGameId>-<cbbdTeamId>". The leading numeric
  // prefix is shared by both teams' rows for the same game, and is the key for
  // the per-game sidecars (game-box-by-year, game-players/). Use gameKey() to
  // take that prefix rather than splitting on "-" ad hoc.
  game_id?: string | null;
  is_home: boolean | null;
  is_neutral: boolean | null;
  won: boolean | null;
  pts_scored: number | null;
  pts_against: number | null;
  // Diffs (team vs opp). Present on most rows, occasionally null.
  pts_diff?: number | null;
  reb_diff?: number | null;
  orb_diff?: number | null;
  tov_diff?: number | null;
  fbpts_diff?: number | null;
  fg3_made_diff?: number | null;
  // Shooting % for the team in this game.
  efg_pct?: number | null;
  ts_pct?: number | null;
  fg3_pct?: number | null;
  ft_pct?: number | null;
  // Optional round label, attached only when the GameLog is being rendered
  // inside a tournament-themed ticker (e.g. March Madness resume). One of
  // "R1" "R2" "S16" "E8" "F4" "NC" — see SHORT_ROUND in coach page.
  tournamentRound?: string | null;
};
const _gameLogsCache = new Map<number, GameLog[]>();
export async function readGameLogsForYear(year: number): Promise<GameLog[]> {
  if (_gameLogsCache.has(year)) return _gameLogsCache.get(year)!;
  try {
    const raw = await readJson<GameLog[]>(`game-logs-by-year/${year}.json`);
    // Drop preseason exhibitions — they aren't real results and would pollute
    // records, schedules and win% everywhere these logs are consumed.
    const games = raw.filter((g) => !isExhibitionGame(g.game_date, year));
    _gameLogsCache.set(year, games);
    return games;
  } catch {
    _gameLogsCache.set(year, []);
    return [];
  }
}

// Earliest season-year we have player data for. Used by the freshman pass in
// readRankedPlayerIds — keep in sync with the export pipeline.
const FRESHMAN_SCAN_START_YEAR = 2013;

let _rankedPlayerIdsCache: Set<number> | null = null;
export async function readRankedPlayerIds(): Promise<Set<number>> {
  if (_rankedPlayerIdsCache) return _rankedPlayerIdsCache;
  const ids = new Set<number>();
  try {
    const files = await fs.readdir(path.join(DATA, "player-ranks"));
    for (const f of files) {
      if (!f.endsWith(".json")) continue;
      const n = parseInt(f.replace(".json", ""), 10);
      if (Number.isFinite(n)) ids.add(n);
    }
  } catch { /* no rank files yet — fall through to freshman pass */ }

  // Freshman pass: walk every year's players-by-year file, track each
  // bart_player_id's MOST RECENT (year, class). If their latest season was a
  // freshman year, they get a profile page regardless of stat thresholds.
  // Captures both current-year freshmen and one-and-done careers.
  try {
    const latestByBartId = new Map<number, { year: number; cls: string | null }>();
    for (let year = FRESHMAN_SCAN_START_YEAR; year <= LATEST_PLAYER_YEAR; year++) {
      let list: StaticPlayerRow[] = [];
      try {
        list = await readJson<StaticPlayerRow[]>(`players-by-year/${year}.json`);
      } catch { continue; }
      for (const p of list) {
        const bartId = p.bart_player_id;
        if (bartId == null || !Number.isFinite(bartId)) continue;
        const prev = latestByBartId.get(bartId);
        if (!prev || prev.year < year) {
          latestByBartId.set(bartId, { year, cls: p.class ?? null });
        }
      }
    }
    for (const [bartId, latest] of latestByBartId) {
      if (latest.cls === "Fr") ids.add(bartId);
    }
  } catch { /* tolerate any I/O hiccup — ranked set is still useful */ }

  // Manual page-includes — notable players who don't clear the ranking baseline
  // or the freshman pass but should still get a profile page. Keep in sync with
  // MANUAL_PROFILE_IDS in scripts/prune-search-index.mjs.
  for (const id of MANUAL_PROFILE_IDS) ids.add(id);

  _rankedPlayerIdsCache = ids;
  return ids;
}

// Hand-picked profile pages (by bart_player_id). See note in readRankedPlayerIds.
export const MANUAL_PROFILE_IDS: readonly number[] = [
  73737, // Tommy Murr (Lipscomb) — requested by hand
];

// Newest season we'll scan for the freshman pass. Mirrors LATEST_YEAR in
// coaches.ts; duplicated here to avoid a circular import.
const LATEST_PLAYER_YEAR = 2026;

/**
 * Per-player situational splits derived from the box-score data: home/away,
 * win/loss, conf/non-conf, plus best/worst game per season. Pre-computed by
 * scripts/compute-player-splits.mjs.
 */
export type SplitAgg = {
  games: number;
  ppg: number; rpg: number; apg: number; spg: number; bpg: number; tov_pg: number;
  fg_pct: number | null;
  fg3_pct: number | null;
  ft_pct: number | null;
  ts_pct: number | null;
} | null;

export type GameSummary = {
  date: string | null;
  opp: string | null;
  is_home: boolean | null;
  is_neutral: boolean | null;
  won: boolean | null;
  mins: number | null;
  pts: number | null;
  reb: number | null;
  ast: number | null;
  stl: number | null;
  blk: number | null;
  tov: number | null;
  fgm: number | null; fga: number | null;
  fgm3: number | null; fga3: number | null;
  ftm: number | null; fta: number | null;
};

export type PlayerSplitsSeason = {
  year: number;
  splits: {
    home: SplitAgg;
    away: SplitAgg;
    neutral: SplitAgg;
    win: SplitAgg;
    loss: SplitAgg;
    conf: SplitAgg;
    nonConf: SplitAgg;
    all: SplitAgg;
  };
  bestGame: GameSummary | null;
  worstGame: GameSummary | null;
};
export type PlayerSplits = {
  bartId: number;
  seasonSplits: PlayerSplitsSeason[];
};
export async function readPlayerSplits(bartId: number): Promise<PlayerSplits | null> {
  try {
    return await readJson<PlayerSplits>(`player-splits/${bartId}.json`);
  } catch {
    return null;
  }
}

/**
 * Look up a player's portal entry by their Bart Torvik ID. Returns the latest
 * entry (most recently updated) when the player has multiple — players who
 * enter and re-enter the portal across cycles can have several rows.
 */
/**
 * One player's full game log, every season. Read at BUILD time from
 * public/data/ — the directory is stripped out of `out/` and served from R2 at
 * runtime, but it is on disk while the pages are generated, so the hero can
 * draw the season's shape without shipping a fetch.
 *
 * Returns [] rather than throwing: a player with no located games (pre-2024
 * seasons, or a roster addition who has not played) still gets a hero, just
 * without the per-game charts.
 */
export type PlayerGameRow = {
  year: number;
  game_date: string | null;
  opp_team_market: string | null;
  is_home: boolean | null;
  is_neutral: boolean | null;
  won: boolean | null;
  mins: number | null;
  pts_scored: number | null;
  reb: number | null;
  ast: number | null;
  ts_pct: number | null;
};

export async function readPlayerGames(bartId: number): Promise<PlayerGameRow[]> {
  try {
    const body = await readJson<{ games: PlayerGameRow[] }>(`player-games/${bartId}.json`);
    return Array.isArray(body.games) ? body.games : [];
  } catch {
    return [];
  }
}

export async function readPortalEntryForBartId(bartId: number): Promise<PortalEntry | null> {
  const all = await readPortal();
  const matches = all.filter((e) => e.bart_player_id === bartId);
  if (matches.length === 0) return null;
  matches.sort((a, b) => (b.date_updated ?? "").localeCompare(a.date_updated ?? ""));
  return matches[0]!;
}

export async function readPlayer(bartId: number): Promise<{
  bart_player_id: number;
  seasons: Array<{
    year: number;
    team_name: string;
    team_conference: string | null;
    class: string | null;
    raw_row: Array<string | number | null> | null;
    games: number | null;
    notes: string | null;
    projection: number | null;
    /**
     * The CBBD-derived aggregates (scripts/build-player-season-adv.mjs). Only
     * the fields the career table reads are declared; the object carries more.
     * Absent for 2021, which has no player box in the archive at all.
     */
    advanced_stats: { gs: number | null; tov: number | null; tov_pg: number | null } | null;
  }>;
} | null> {
  try {
    return await readJson(`player/${bartId}.json`);
  } catch {
    return null;
  }
}

export async function readConferences(year: number): Promise<string[]> {
  const all = await readJson<Record<string, string[]>>("conferences.json");
  return all[String(year)] ?? [];
}

/**
 * One team's seasons with percentiles already computed, or null if that team
 * has not been baked yet.
 *
 * Written by scripts/build-team-seasons.mts — see the long note at the top of
 * that file for why the percentiles cannot be computed here. The short version
 * is that a chip ranks a team-season against all ~360 teams from its year, and
 * readAllTeams() above has no cache, so doing it per page would re-parse a
 * 12 MB file on each of 5,009 team pages.
 *
 * NULL IS A NORMAL ANSWER, not an error. The bake accepts a --team flag so a
 * change can be tried on one team before it is committed to all 368, and a team
 * that has not been baked simply falls back to the older seasons table. That
 * makes a partial bake a safe state for the site to be in rather than a broken
 * one, which is the whole point of allowing it.
 */
export async function readTeamSeasonGrid(slug: string): Promise<TeamGridSeason[] | null> {
  try {
    return await readJson<TeamGridSeason[]>(`team-seasons/${slug}.json`);
  } catch {
    return null;
  }
}

/**
 * A baked team-season row. This is `TeamRow` from team-filters, but declared
 * structurally here so static-data does not have to import the explorer's
 * module graph — only the fields the By season grid reads are named, and the
 * index signature carries the rest of the stat columns the grid addresses by
 * key from the shared column model.
 */
export type TeamGridSeason = {
  team_name: string;
  team_conference: string | null;
  team_year: number;
  record: string | null;
  pct: Record<string, number | null>;
} & Record<string, unknown>;
