/**
 * Build-time static data loader. All reads go through `public/data/*.json`
 * (generated by `npm run export:data`) — Supabase is never touched at runtime.
 *
 * Used by server components / generateStaticParams. The functions are async to
 * preserve the existing call sites that expected promises.
 */
import fs from "node:fs/promises";
import path from "node:path";

const DATA = path.resolve("public/data");

async function readJson<T>(rel: string): Promise<T> {
  const text = await fs.readFile(path.join(DATA, rel), "utf8");
  return JSON.parse(text) as T;
}

// ---------- types matching the static JSON shape ----------
export type RankedStat = {
  key: string;
  label: string;
  format: "num1" | "num2" | "pct1" | "intDiff";
  value: number;
  rank: number;
  total: number;
};


export type StaticTeamSeasonRow = {
  id: number;
  name: string;
  conference: string | null;
  year: number;
  bta_rtg: number | null;            // pre-computed at build time
  bta_rank: number | null;           // rank within season cohort (1 = best)
  // Aggregated at export time from game_logs: count of (wins, losses, games)
  // where REB Diff > 0 AND FBP Diff > 0 AND 3PM Diff > 0 for that game.
  four_factor_record?: { wins: number; losses: number; games: number } | null;
  coach?: string | null;             // head coach (synced separately; nullable)
  // National-rank top-5 strengths + bottom-5 weaknesses for this season.
  // Computed at export time over the year's full D-I cohort. Each entry has
  // its raw value, rank, and total teams ranked so the UI can render
  // percentile-colored chips.
  national_ranks?: {
    top: Array<RankedStat>;
    bottom: Array<RankedStat>;
  };
  team_trank_stats: {
    rank: number | null; record: string | null;
    wins: number | null; losses: number | null;
    adjoe: number | null; adjde: number | null;
    adjt: number | null;
    wab: number | null; sos: number | null;
    ncsos: number | null; consos: number | null;
  };
  team_cbba_stats: {
    efg_pct: number | null; ts_pct: number | null;
    tov_pct: number | null; orb_pct: number | null;
    fta_rate: number | null; fg3_pct: number | null;
    fg3a_rate: number | null; ast_pct: number | null;
    efg_pct_def: number | null; tov_pct_def: number | null;
    orb_pct_def: number | null; fg3_pct_def: number | null;
    ortg: number | null; drtg: number | null;
    net_rtg: number | null; ortg_adj: number | null;
    drtg_adj: number | null; net_rtg_adj: number | null;
    pace: number | null; pace_adj: number | null;
    fbpts_pct: number | null; pitp_pct: number | null;
    fg3_made_diff?: number | null; orb_diff_ct?: number | null;
    reb_diff?: number | null; fbpts_diff?: number | null;
    potov_diff?: number | null;
  } | null;
};

export type StaticPlayerRow = {
  id: number;
  bart_player_id: number | null;
  name: string;
  year: number;
  class: string | null;
  height: string | null;
  hometown: string | null;
  teams: { id: number; name: string; conference: string | null } | Array<{ id: number; name: string; conference: string | null }>;
  player_bart_stats: {
    raw_row: Array<string | number | null> | null;
    games: number | null;
    notes: string | null;
    projection: number | null;
  };
};

export type StaticIndex = {
  teamSlugs: string[];
  playerIds: number[];
  generated_at: string;
};

// ---------- public API ----------
export async function readIndex(): Promise<StaticIndex> {
  return readJson<StaticIndex>("index.json");
}

export async function readAllTeams(): Promise<StaticTeamSeasonRow[]> {
  return readJson<StaticTeamSeasonRow[]>("teams-all.json");
}

export async function readTeam(slug: string): Promise<{ name: string; seasons: StaticTeamSeasonRow[] } | null> {
  try {
    return await readJson<{ name: string; seasons: StaticTeamSeasonRow[] }>(`team/${slug}.json`);
  } catch {
    return null;
  }
}

export async function readPlayersForYear(year: number): Promise<StaticPlayerRow[]> {
  return readJson<StaticPlayerRow[]>(`players-by-year/${year}.json`);
}

/**
 * One transfer-portal entry for a specific player. Surface this on the
 * player profile hero when the player has committed elsewhere — we strike
 * through their current school and show the new destination.
 */
export type PortalEntry = {
  cbba_player_id: number;
  bart_player_id: number | null;
  name: string;
  status: "Active" | "Transferred" | "Withdrew";
  team_from: string | null;
  conf_from: string | null;
  team_to: string | null;
  conf_to: string | null;
  date_entered: string | null;
  date_updated: string | null;
};

let _portalCache: PortalEntry[] | null = null;
async function readPortal(): Promise<PortalEntry[]> {
  if (_portalCache) return _portalCache;
  try {
    const portal = await readJson<{ entries: PortalEntry[] }>("portal.json");
    _portalCache = portal.entries;
    return _portalCache;
  } catch {
    return [];
  }
}

/**
 * Per-player percentile ranks across ~20 stats, cohorted by year × position
 * bucket (G/F/C). Pre-computed by scripts/compute-player-ranks.mjs.
 */
export type PlayerStatRank = {
  value: number;
  percentile: number;     // 1-100 (higher = better, with direction already applied)
};
export type PlayerRanksSeason = {
  year: number;
  bucket: "G" | "F" | "C";
  cohortSize: number;
  stats: Record<string, PlayerStatRank>;
};
export type PlayerRanks = {
  bartId: number;
  seasonRanks: PlayerRanksSeason[];
};
export async function readPlayerRanks(bartId: number): Promise<PlayerRanks | null> {
  try {
    return await readJson<PlayerRanks>(`player-ranks/${bartId}.json`);
  } catch {
    return null;
  }
}

/**
 * Per-player situational splits derived from the box-score data: home/away,
 * win/loss, conf/non-conf, plus best/worst game per season. Pre-computed by
 * scripts/compute-player-splits.mjs.
 */
export type SplitAgg = {
  games: number;
  ppg: number; rpg: number; apg: number; spg: number; bpg: number; tov_pg: number;
  fg_pct: number | null;
  fg3_pct: number | null;
  ft_pct: number | null;
  ts_pct: number | null;
} | null;

export type GameSummary = {
  date: string | null;
  opp: string | null;
  is_home: boolean | null;
  is_neutral: boolean | null;
  won: boolean | null;
  mins: number | null;
  pts: number | null;
  reb: number | null;
  ast: number | null;
  stl: number | null;
  blk: number | null;
  tov: number | null;
  fgm: number | null; fga: number | null;
  fgm3: number | null; fga3: number | null;
  ftm: number | null; fta: number | null;
};

export type PlayerSplitsSeason = {
  year: number;
  splits: {
    home: SplitAgg;
    away: SplitAgg;
    neutral: SplitAgg;
    win: SplitAgg;
    loss: SplitAgg;
    conf: SplitAgg;
    nonConf: SplitAgg;
    all: SplitAgg;
  };
  bestGame: GameSummary | null;
  worstGame: GameSummary | null;
};
export type PlayerSplits = {
  bartId: number;
  seasonSplits: PlayerSplitsSeason[];
};
export async function readPlayerSplits(bartId: number): Promise<PlayerSplits | null> {
  try {
    return await readJson<PlayerSplits>(`player-splits/${bartId}.json`);
  } catch {
    return null;
  }
}

/**
 * Look up a player's portal entry by their Bart Torvik ID. Returns the latest
 * entry (most recently updated) when the player has multiple — players who
 * enter and re-enter the portal across cycles can have several rows.
 */
export async function readPortalEntryForBartId(bartId: number): Promise<PortalEntry | null> {
  const all = await readPortal();
  const matches = all.filter((e) => e.bart_player_id === bartId);
  if (matches.length === 0) return null;
  matches.sort((a, b) => (b.date_updated ?? "").localeCompare(a.date_updated ?? ""));
  return matches[0]!;
}

export async function readPlayer(bartId: number): Promise<{
  bart_player_id: number;
  seasons: Array<{
    year: number;
    team_name: string;
    team_conference: string | null;
    class: string | null;
    raw_row: Array<string | number | null> | null;
    games: number | null;
    notes: string | null;
    projection: number | null;
  }>;
} | null> {
  try {
    return await readJson(`player/${bartId}.json`);
  } catch {
    return null;
  }
}

export async function readConferences(year: number): Promise<string[]> {
  const all = await readJson<Record<string, string[]>>("conferences.json");
  return all[String(year)] ?? [];
}
